First pass at OPIE 2.32 support.
svn path=/trunk/; revision=1407

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -47,8 +47,6 @@ AC_CHECK_FUNC(inet_addr,
     AC_MSG_RESULT(using libc's inet_addr),
     AC_CHECK_LIB(nsl,inet_addr))
 
-AC_CHECK_LIB(opie,opiegenerator)
-
 dnl Port hack for Interactive UNIX System V/386 Release 3.2
 AC_CHECK_LIB(cposix, strchr,
 		[EXTRADEFS="$EXTRADEFS -D_SYSV3"
@@ -156,12 +154,19 @@ AC_ARG_ENABLE(POP2,
 	[with_POP2=no])
 test "$with_POP2" = "yes" && AC_DEFINE(POP2_ENABLE)
 
-###	use option --enable-OPIE to compile in the OPIE support
-AC_ARG_ENABLE(OPIE,
-	[  --enable-OPIE        compile in OPIE protocol support (obsolete)],
-	[with_OPIE=$enableval],
-	[with_OPIE=no])
-test "$with_OPIE" = "yes" && AC_DEFINE(OPIE_ENABLE)
+###	use option --enable-opie to compile in the OPIE support
+AC_ARG_ENABLE(opie,
+	[  --enable-opie        support OTP through the OPIE library],
+	[with_opie=$enableval],
+	[with_opie=no])
+if test "$with_opie" = "yes";
+then
+    AC_CHECK_HEADER(opie,, 
+	[echo 'configure: cannot find <opie.h>, which is required for OPIE support.'; exit 1])
+    AC_CHECK_LIB(opie,opiegenerator,, 
+	[echo 'configure: cannot find libopie, which is required for OPIE support.'; exit 1])
+    AC_DEFINE(OPIE,1)
+fi
 
 ###	use option --with-kerberos=DIR to point at a Kerberos directory
 AC_ARG_WITH(kerberos,
