Alll of Craig Metz's changes for IPv6 and IPSEC except the POP3 stuff.
svn path=/trunk/; revision=1630

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -190,6 +190,23 @@ AC_ARG_ENABLE(opie,
           AC_DEFINE(OPIE,1) ],
 	[with_opie=no])
 
+AC_ARG_ENABLE(inet6,
+	[  --enable-inet6       support IPv6 (requires the inet6-apps library)],
+        [ unset ac_cv_lib_inet6_getaddrinfo; AC_CHECK_LIB(inet6, getaddrinfo,,
+	[ unset ac_cv_lib_inet6_getaddrinfo; LDFLAGS="$LDFLAGS -L/usr/inet6/lib"; AC_CHECK_LIB(inet6, getaddrinfo,,
+        [ echo 'configure: cannot find libinet6, which is required for IPv6 support.'; exit 1]) ])
+          AC_DEFINE(INET6, 1) ])
+
+AC_ARG_ENABLE(netsec,
+	[  --enable-netsec      support network security (req. the inet6-apps library)],
+        [ unset ac_cv_lib_inet6_net_security_strtorequest; AC_CHECK_LIB(inet6, net_security_strtorequest,,
+	[ unset ac_cv_lib_inet6_net_security_strtorequest; LDFLAGS="$LDFLAGS -L/usr/inet6/lib"; AC_CHECK_LIB(inet6, net_security_strtorequest,,
+        [ echo 'configure: cannot find net_security_strtorequest in libinet6, which is required';
+          echo '           for network security support. Either it does not exist, or it was';
+          echo '           not built with network security support enabled.';
+          exit 1]) ])
+          AC_DEFINE(NETSEC, 1) ])
+  
 ###	use option --with-gssapi=DIR to compile in GSSAPI support
 AC_ARG_WITH(gssapi,
 	[  --with-gssapi[=DIR]  compile in GSSAPI support using libraries in DIR])
