Ready to send this to Mike.
svn path=/trunk/; revision=2649

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -281,31 +281,41 @@ AC_ARG_ENABLE(opie,
 	[  --enable-opie           support OTP through the OPIE library],
 	[ AC_CHECK_HEADER(opie.h,, [echo 'configure: cannot find <opie.h>, which is required for OPIE support.'; exit 1])
           AC_CHECK_LIB(opie,opiegenerator,, [echo 'configure: cannot find libopie, which is required for OPIE support.'; exit 1])
-          AC_DEFINE(OPIE,1) ],
+          with_opie=$enableval],
 	[with_opie=no])
+test "$with_opie" = "yes" && AC_DEFINE(OPIE_ENABLE)
 
 AC_ARG_ENABLE(inet6,
 	[  --enable-inet6          support IPv6 (requires the inet6-apps library)],
-        [ unset ac_cv_lib_inet6_getaddrinfo; AC_CHECK_LIB(inet6, getaddrinfo,,
-	[ unset ac_cv_lib_inet6_getaddrinfo; LDFLAGS="$LDFLAGS -L/usr/inet6/lib"; AC_CHECK_LIB(inet6, getaddrinfo,,
-        [ echo 'configure: cannot find libinet6, which is required for IPv6 support.'; exit 1]) ])
-          AC_DEFINE(INET6, 1) ])
+        [ unset ac_cv_lib_inet6_getaddrinfo; AC_CHECK_LIB(inet6,getaddrinfo,,
+	  [ unset ac_cv_lib_inet6_getaddrinfo;
+	    LDFLAGS="$LDFLAGS -L/usr/inet6/lib";
+            AC_CHECK_LIB(inet6, getaddrinfo,,
+              [ echo 'configure: cannot find libinet6, which is required for IPv6 support.'; 
+	      exit 1]) ]) ]
+	[with_inet6=no])
+test "$with_inet6" = "yes" && AC_DEFINE(INET6_ENABLE)
 
 AC_ARG_ENABLE(netsec,
 	[  --enable-netsec         support network security (requires inet6-apps library)],
         [ unset ac_cv_lib_inet6_net_security_strtorequest; AC_CHECK_LIB(inet6, net_security_strtorequest,,
-	[ unset ac_cv_lib_inet6_net_security_strtorequest; LDFLAGS="$LDFLAGS -L/usr/inet6/lib"; AC_CHECK_LIB(inet6, net_security_strtorequest,,
-        [ echo 'configure: cannot find net_security_strtorequest in libinet6, which is required';
-          echo '           for network security support. Either it does not exist, or it was';
-          echo '           not built with network security support enabled.';
-          exit 1]) ])
-          unset ac_cv_header_net_security_h; AC_CHECK_HEADER(net/security.h,,
-        [ unset ac_cv_header_net_security_h; CPPFLAGS="$CPPFLAGS -I/usr/inet6/include"; CFLAGS="$CFLAGS -I/usr/inet6/include"; AC_CHECK_HEADER(net/security.h,,
-	[ echo 'configure: cannot find <net/security.h>, which is required for network security';
-          echo '           support.';
-          exit 1]) ])
-          AC_DEFINE(NET_SECURITY, 1) ])
-  
+	  [ unset ac_cv_lib_inet6_net_security_strtorequest;
+            LDFLAGS="$LDFLAGS -L/usr/inet6/lib"; 
+            AC_CHECK_LIB(inet6, net_security_strtorequest,,
+            [ echo 'configure: cannot find net_security_strtorequest in libinet6, which is required';
+              echo '           for network security support. Either it does not exist, or it was';
+              echo '           not built with network security support enabled.';
+              exit 1]) ])
+        unset ac_cv_header_net_security_h; AC_CHECK_HEADER(net/security.h,,
+        [ unset ac_cv_header_net_security_h; 
+	CPPFLAGS="$CPPFLAGS -I/usr/inet6/include"; 
+	CFLAGS="$CFLAGS -I/usr/inet6/include"; AC_CHECK_HEADER(net/security.h,,
+	  [ echo 'configure: cannot find <net/security.h>, which is required';
+          echo '             for network security support.';
+          exit 1]) ]) ]
+	[with_netsec=no])
+test "$with_netsec" = "yes" && AC_DEFINE(NET_SECURITY)
+
 ###	use option --with-kerberos5=DIR to point at a Kerberos 5 directory
 AC_ARG_WITH(kerberos5,
 	[  --with-kerberos5=DIR    point fetchmail compilation at a Kerberos 5 directory])
