Corrected OTP support.
svn path=/trunk/; revision=1610

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -182,19 +182,13 @@ AC_ARG_ENABLE(RPA,
 	[with_RPA=no])
 test "$with_RPA" = "yes" && AC_DEFINE(RPA_ENABLE)
 
-###	use option --enable-OPIE to compile in the OPIE support
+###	use option --enable-opie to compile in the OPIE support
 AC_ARG_ENABLE(opie,
-	[  --enable-OPIE        support OTP through the OPIE library],
-	[with_opie=$enableval],
+	[  --enable-opie        support OTP through the OPIE library],
+	[ AC_CHECK_HEADER(opie.h,, [echo 'configure: cannot find <opie.h>, which is required for OPIE support.'; exit 1])
+          AC_CHECK_LIB(opie,opiegenerator,, [echo 'configure: cannot find libopie, which is required for OPIE support.'; exit 1])
+          AC_DEFINE(OPIE,1) ],
 	[with_opie=no])
-if test "$with_opie" = "yes";
-then
-    AC_CHECK_HEADER(opie.h,, 
-	[echo 'configure: cannot find <opie.h>, which is required for OPIE support.'; exit 1])
-    AC_CHECK_LIB(opie,opiegenerator,, 
-	[echo 'configure: cannot find libopie, which is required for OPIE support.'; exit 1])
-    AC_DEFINE(OPIE,1)
-fi
 
 ###	use option --with-gssapi=DIR to compile in GSSAPI support
 AC_ARG_WITH(gssapi,
